#!/bin/sh
#
# strip output of IPython Notebooks
# add this as `.git/hooks/pre-commit`
# to run every time you commit a notebook
#

# Find notebooks
NBS=`git diff --cached --name-only --diff-filter=ACM | grep -v '\.ipynb_checkpoints/' | grep -a '.ipynb$' | uniq`

# Remove outputs from all notebooks
for NB in $NBS ; do
    echo "Removing outputs from $NB"
    jupyter nbconvert --ClearOutputPreprocessor.enabled=True --inplace "$NB"
    git add "$NB"
done
